# Generated by Django 4.2.19 on 2025-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='same_address',
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
