# Generated by Django 4.2.19 on 2025-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_donation_same_address_alter_donation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='communication_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='same_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='permanent_address',
            field=models.TextField(default=''),
        ),
    ]
