# Generated by Django 4.2.19 on 2025-02-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_donation_communication_address_donation_same_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='communication_address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='same_address',
        ),
    ]
