# Generated by Django 4.2.19 on 2025-02-28 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_donation_communication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
