# Generated by Django 4.2.19 on 2025-02-28 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='permanent_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
