# Generated by Django 4.2.19 on 2025-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donation_user_alter_donation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
