# Generated by Django 4.2.19 on 2025-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_donation_donor_name_alter_donation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
