# Generated by Django 4.2.19 on 2025-03-03 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_alter_donation_donor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('siblings', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('college_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('department_head_contact', models.CharField(max_length=15)),
                ('semester_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='documents/aadhar_cards/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/pan_cards/')),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='documents/bank_passbooks/')),
                ('college_bonafide', models.FileField(blank=True, null=True, upload_to='documents/college_bonafides/')),
                ('extracurricular_certificate', models.FileField(blank=True, null=True, upload_to='documents/extracurricular_certificates/')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.AlterField(
            model_name='donation',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pancard',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='permanent_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
