# Generated by Django 4.2.19 on 2025-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_scholarshipapplication_remove_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
