# Generated by Django 4.2.19 on 2025-03-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_scholarshipapplication_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
